type File @model {
  contentType: String!
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  secret: String! @isUnique
  size: Int!
  updatedAt: DateTime!
  url: String! @isUnique
}

type Post @model {
  createdAt: DateTime!
  createdBy: String!
  id: ID! @isUnique
  title: String!
  updatedAt: DateTime!
  body: String
  thumbnail: String
  image: String
}

type User @model {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
}

type MarketDashboard @model {
  count: Int!
  date: DateTime!
  id: ID! @isUnique
  nvlavg: Float!
  nvlcount: Int!
  nvlmax: Float!
  nvltavg: Float!
  nvltcount: Int!
  nvltmax: Float!
  vaqavg: Float!
  vaqcount: Int!
  vaqmax: Float!
  teravg: Float!
  tercount: Int!
  termax: Float!
  vacavg: Float!
  vaccount: Int!
  vacmax: Float!
  conavg: Float!
  concount: Int!
  conmax: Float!
  toravg: Float!
  torcount: Int!
  tormax: Float!
  createdAt: DateTime!
  updatedAt: DateTime!
  location: MarketLocation!
}

type GrowDashboard @model {
  id: ID! @isUnique
  date: DateTime!
  tero160: Float!
  tero180: Float!
  tero200: Float!
  nov230: Float!
  nov260: Float!
  nov300: Float!
  tera0: Float!
  tera150: Float!
  tera190: Float!
  vaq210: Float!
  vaq250: Float!
  vaqpren: Float!
  vacnuepren: Float!
  vacusdpren: Float!
  vacnuecri: Float!
  vacusdcri: Float!
  location: String!
  seller: String!
  tero0: Float
}

enum MarketLocation {
  LINIERS
  ROSARIO
}